package com.example.MyBookShopApp.entities;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;

@Entity
@Table(name = "book_review_like")
@ApiModel(description = "entity representing a book review like")
public class BookReviewLike {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private Integer id;

    @ManyToOne
    @JoinColumn(name = "book_review_id", referencedColumnName = "id")
    private BookReview bookReview;

    @ApiModelProperty("like or dislike of a review of a book, like = 1, dislike =-1")
    private Byte value;

    @ApiModelProperty("count of likes of a review")
    private static Integer bookReviewLikesCount = 0;

    @ApiModelProperty("count of dislikes of a review")
    private static Integer bookReviewDislikesCount = 0;

    public BookReviewLike() {
    }

    public BookReviewLike(BookReview bookReview, Byte value) {
        this.bookReview = bookReview;
        this.value = value;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public BookReview getBookReview() {
        return bookReview;
    }

    public void setBookReview(BookReview bookReview) {
        this.bookReview = bookReview;
    }

    public Byte getValue() {
        return value;
    }

    public void setValue(Byte value) {
        this.value = value;
    }

    public static Integer getBookReviewLikesCount() {
        return bookReviewLikesCount;
    }

    public static void setBookReviewLikesCount(Integer bookReviewLikesCount) {
        BookReviewLike.bookReviewLikesCount = bookReviewLikesCount;
    }

    public static Integer getBookReviewDislikesCount() {
        return bookReviewDislikesCount;
    }

    public static void setBookReviewDislikesCount(Integer bookReviewDislikesCount) {
        BookReviewLike.bookReviewDislikesCount = bookReviewDislikesCount;
    }
}
