package com.example.MyBookShopApp.data;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "book_review")
@ApiModel(description = "entity representing a book review")
public class BookReview {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private Integer id;

    @ApiModelProperty("date and time of the book review")
    private LocalDateTime dateTime;

    @ManyToOne
    @JoinColumn(name = "book_id", referencedColumnName = "id")
    @ApiModelProperty("id of the reviewed book")
    private Book book;

    @ManyToOne
    @JoinColumn(name = "user_id", referencedColumnName = "id")
    @ApiModelProperty("id of the user, who reviewed the book")
    private User user;

    @ApiModelProperty("text of the book review")
    private String text;

    public BookReview() {
    }

    public BookReview(LocalDateTime dateTime, Book book, User user, String text) {
        this.dateTime = dateTime;
        this.book = book;
        this.user = user;
        this.text = text;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public LocalDateTime getDateTime() {
        return dateTime;
    }

    public void setDateTime(LocalDateTime dateTime) {
        this.dateTime = dateTime;
    }

    public Book getBook() {
        return book;
    }

    public void setBook(Book book) {
        this.book = book;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }
}
